vich_uploader:
    db_driver: orm


    mappings:
        hotel_images:
            uri_prefix: /images/hotel
            upload_destination: '%kernel.project_dir%/public/images/hotel'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\UniqidNamer
        suites_images:
            uri_prefix: /images/suite
            upload_destination: '%kernel.project_dir%/public/images/suite'
            inject_on_load: false
            delete_on_update: true
            delete_on_remove: true
            namer: Vich\UploaderBundle\Naming\UniqidNamer